### ISSUE TITLE
Crash after updating RubyMotion to 2.32

### ISSUE THREAD

**Issue by DiogoAndre** [motion-kit/motion-kit#75]
My layout has the following to style a UIButton:

``` ruby
  def start_button_style
    title 'Start'
    size_to_fit
    title_color "37A8A4".to_color, state: UIControlStateNormal
    title_color "37ffA4".to_color, state: UIControlStateHighlighted    
    font UIFont.fontWithName('Helvetica Neue', size: 25.0)
  end
```

I was working fine before updating RM to the latest version, but now I'm getting some errors that trace back to the `base_layout.rb` file from MotionKit:

`2014-09-02 15:43:03.622 inLabor[83815:70b] base_layout.rb:179:in `objc_version:': undefined method `values' for 1:Fixnum (NoMethodError)`

After some tinkering, I traced it back to the `title_color` lines in the code above. I can use either one by itself, but not the two lines at the same time. 

Am I doing something wrong, or is this some kind of bug?

Thanks!
